---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: bash
    tag: '4.4'

inputs:
  - name: elasticsearch
  - name: x-pack-elasticsearch
    path: elasticsearch-extra/x-pack-elasticsearch

run:
  path: ./x-pack-elasticsearch/ci/scripts/run_tests.sh
