---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: '3.5'

inputs:
  - name: elasticsearch
  - name: x-pack-elasticsearch

run:
  path: echo
  args: [hello world]
